version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: health_care
      POSTGRES_PASSWORD: "BZ06vxCjujbU7DWFLUhbVKbzpxKbIRas"
    volumes:
      - health_care_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Ge0Sbv5ayVpt2pqOMPaF0gO6QQHE5jyp"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  health_care_data:
