
include: package:very_good_analysis/analysis_options.yaml

analyzer:

  language:
    strict-raw-types: false
    
linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false   
    use_build_context_synchronously: false
    prefer_asserts_with_message: false
    unawaited_futures: false